export const staffToCreate = [
        {
            name: 'Amelie Griffith',
            password: 'adminhotel@example.com',
            email: 'amelie@example.com',
            role: 'ADMIN',
            status: 'ACTIVE',
            availability: 'AVAILABLE',
        },
        {
            name: 'Kylan Gentry',
            pinCode: '2478',
            email: 'kylantest@example.com',
            role: 'CLEANER',
            status: 'ACTIVE',
            availability: 'AVAILABLE',
        },
        {
            name: 'Antonio Crosby',
            pinCode: '1138',
            email: 'antonio@example.com',
            role: 'REPAIRMAN',
            status: 'ACTIVE',
            availability: 'DAY_OFF',
        },
        {
            name: 'Marceline Avila',
            pinCode: '1911',
            email: 'marceline@example.com',
            role: 'CLEANER',
            status: 'ACTIVE',
            availability: 'SICK_LEAVE',
        },
        {
            name: 'Anna Vance',
            pinCode: '1912',
            email: 'annatest@example.com',
            role: 'CLEANER',
            status: 'INACTIVE',
            availability: 'UNAVAILABLE',
        },
        {
            name: 'Oleh  Fletcher',
            pinCode: '3321',
            email: 'olehrepair@example.com',
            role: 'REPAIRMAN',
            status: 'ACTIVE',
            availability: 'AVAILABLE',
        },
        {
            name: 'Maria Thornton',
            pinCode: '5566',
            email: 'mariatest@example.com',
            role: 'CLEANER',
            status: 'TERMINATED',
            availability: 'UNAVAILABLE',
        },
        {
            name: 'Sophia Anderson',
            pinCode: '8899',
            email: 'sophia@example.com',
            role: 'CLEANER',
            status: 'ACTIVE',
            availability: 'AVAILABLE',
        },
        {
            name: 'Robert Davis',
            pinCode: '7788',
            email: 'robert@example.com',
            role: 'REPAIRMAN',
            status: 'ACTIVE',
            availability: 'AVAILABLE',
        },
        {
            name: 'James Taylor',
            pinCode: '4455',
            email: 'james@example.com',
            role: 'REPAIRMAN',
            status: 'ACTIVE',
            availability: 'SICK_LEAVE',
        },
        {
            name: 'Emma Thomas',
            pinCode: '6677',
            email: 'emma@example.com',
            role: 'CLEANER',
            status: 'ACTIVE',
            availability: 'DAY_OFF',
        },
        {
            name: 'Daniel Moore',
            pinCode: '9900',
            email: 'daniel@example.com',
            role: 'REPAIRMAN',
            status: 'INACTIVE',
            availability: 'VACATION',
        },
        {
            name: 'Laura White',
            pinCode: '1234',
            email: 'laura@example.com',
            role: 'CLEANER',
            status: 'ACTIVE',
            availability: 'AVAILABLE',
        },
        {
            name: 'George Martin',
            pinCode: '4321',
            email: 'george@example.com',
            role: 'REPAIRMAN',
            status: 'TERMINATED',
            availability: 'UNAVAILABLE',
        },
        {
            name: 'Nina Clark',
            pinCode: '2468',
            email: 'nina@example.com',
            role: 'CLEANER',
            status: 'ACTIVE',
            availability: 'VACATION',
        },
    ];